POC junitreport

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -22,7 +22,9 @@ jobs:
         java:
           - 17
           - 21
-          - 25
+	group:
+          - byteman
+          - encrypt
     steps:
       - name: Checkout
         uses: actions/checkout@v6
@@ -34,4 +36,9 @@ jobs:
           cache: maven
       - name: Build with Maven
         # In order to support Windows PowerShell, a space between --define property=true is required.
-        run: mvn --batch-mode --no-transfer-progress verify --define skipTests=true
+        run: mvn --batch-mode --no-transfer-progress verify -Dgroups ${{ matrix.group }}
+      - name: Publish Test Report
+        uses: mikepenz/action-junit-report@v6
+        if: success() || failure() # always run even if the previous step fails
+        with:
+          report_paths: 'target/surefire-reports/junitreports/TEST-*.xml'
