POC junitreport

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -34,4 +34,9 @@ jobs:
           cache: maven
       - name: Build with Maven
         # In order to support Windows PowerShell, a space between --define property=true is required.
-        run: mvn --batch-mode --no-transfer-progress verify --define skipTests=true
+        run: mvn --batch-mode --no-transfer-progress verify
+      - name: Publish Test Report
+        uses: mikepenz/action-junit-report@v6
+        if: success() || failure() # always run even if the previous step fails
+        with:
+          report_paths: 'target/surefire-reports/junitreports/TEST-*.xml'
